window.HerbData = {
  siteName: '本草知识图谱',
  siteTagline: '药材查询、方剂检索、知识图谱与 AI 问答一体化前端',
  nav: [
    { id: 'home', label: '首页', href: 'index.html', icon: 'fa-house' },
    { id: 'search', label: '药材查询', href: 'herb-search.html', icon: 'fa-magnifying-glass' },
    { id: 'graph', label: '知识图谱', href: 'knowledge-graph.html', icon: 'fa-diagram-project' },
    { id: 'qa', label: 'AI 问答', href: 'qa.html', icon: 'fa-comments' },
    { id: 'formula', label: '方剂库', href: 'formula-library.html', icon: 'fa-book-medical' },
    { id: 'design', label: '设计系统', href: 'design-system.html', icon: 'fa-palette' }
  ],
  filters: {
    categories: ['补气药', '补血药', '解表药', '活血药', '安神药', '清热药'],
    regions: ['东北', '华北', '华东', '华中', '西南', '西北'],
    meridians: ['脾', '肺', '肝', '心', '胃', '肾']
  },
  herbs: [
    {
      id: 1,
      name: '人参',
      pinyin: 'Ren Shen',
      aliases: ['红参', '生晒参'],
      category: '补气药',
      region: '东北',
      source: '五加科植物人参的根和根茎',
      nature: '甘、微苦，微温',
      meridian: ['脾', '肺', '心'],
      efficacy: ['大补元气', '复脉固脱', '补脾益肺', '生津养血', '安神益智'],
      usage: '3-9g，另煎兑服；研粉吞服每次 1-2g',
      caution: '实热、湿热内盛或正气不虚者慎用。',
      description: '人参为补气要药，适用于气虚欲脱、脾肺气虚、津伤口渴和心神不宁等证候。',
      composition: ['人参皂苷', '多糖', '挥发油'],
      imageTone: '#2f7651',
      formulaIds: [1, 5, 6]
    },
    {
      id: 2,
      name: '黄芪',
      pinyin: 'Huang Qi',
      aliases: ['绵黄芪', '北芪'],
      category: '补气药',
      region: '华北',
      source: '豆科植物蒙古黄芪或膜荚黄芪的根',
      nature: '甘，微温',
      meridian: ['脾', '肺'],
      efficacy: ['补气升阳', '固表止汗', '利水消肿', '托毒生肌'],
      usage: '9-30g，补气宜炙用，利水托毒宜生用。',
      caution: '表实邪盛、气滞湿阻、阴虚阳亢者慎用。',
      description: '黄芪长于补气升提与固表，常用于气虚自汗、久泻脱肛和表虚易感。',
      composition: ['黄芪甲苷', '黄酮', '多糖'],
      imageTone: '#c67517',
      formulaIds: [1, 6]
    },
    {
      id: 3,
      name: '当归',
      pinyin: 'Dang Gui',
      aliases: ['秦归'],
      category: '补血药',
      region: '西南',
      source: '伞形科植物当归的根',
      nature: '甘、辛，温',
      meridian: ['肝', '心', '脾'],
      efficacy: ['补血活血', '调经止痛', '润肠通便'],
      usage: '6-12g，补血多用身，活血多用尾。',
      caution: '湿热泄泻及出血偏多者慎用。',
      description: '当归既能补血，又善活血，是血虚、血瘀和经行不调场景的常用药材。',
      composition: ['挥发油', '阿魏酸', '多糖'],
      imageTone: '#a83d30',
      formulaIds: [2, 4, 5, 6]
    },
    {
      id: 4,
      name: '甘草',
      pinyin: 'Gan Cao',
      aliases: ['国老', '甜草'],
      category: '补气药',
      region: '西北',
      source: '豆科植物甘草、胀果甘草或光果甘草的根及根茎',
      nature: '甘，平',
      meridian: ['心', '肺', '脾', '胃'],
      efficacy: ['补脾益气', '清热解毒', '祛痰止咳', '缓急止痛', '调和诸药'],
      usage: '2-10g，清热解毒宜生用，补中缓急宜炙用。',
      caution: '不宜长期大量服用；湿盛胀满、水肿者慎用。',
      description: '甘草兼具补益、解毒与调和配伍作用，在方剂中常承担协调药性的角色。',
      composition: ['甘草酸', '甘草黄酮'],
      imageTone: '#14766f',
      formulaIds: [1, 2, 3]
    },
    {
      id: 5,
      name: '麻黄',
      pinyin: 'Ma Huang',
      aliases: ['龙沙', '卑相'],
      category: '解表药',
      region: '华北',
      source: '麻黄科植物草麻黄、中麻黄或木贼麻黄的草质茎',
      nature: '辛、微苦，温',
      meridian: ['肺', '膀胱'],
      efficacy: ['发汗解表', '宣肺平喘', '利水消肿'],
      usage: '2-10g，发汗解表宜生用，平喘多炙用。',
      caution: '表虚自汗、阴虚盗汗、肺肾虚喘者慎用。',
      description: '麻黄偏于宣散，适合风寒束表、肺气不宣的外感与喘咳场景。',
      composition: ['麻黄碱', '伪麻黄碱'],
      imageTone: '#3c7d8c',
      formulaIds: [3]
    },
    {
      id: 6,
      name: '丹参',
      pinyin: 'Dan Shen',
      aliases: ['赤参', '紫丹参'],
      category: '活血药',
      region: '华东',
      source: '唇形科植物丹参的根及根茎',
      nature: '苦，微寒',
      meridian: ['心', '肝'],
      efficacy: ['活血祛瘀', '通经止痛', '清心除烦', '凉血消痈'],
      usage: '10-15g，活血化瘀常规煎服。',
      caution: '孕妇慎用，不宜与藜芦同用。',
      description: '丹参善入血分，常用于血瘀疼痛、心烦不眠及疮痈肿痛。',
      composition: ['丹参酮', '丹酚酸'],
      imageTone: '#7f3d3d',
      formulaIds: [4]
    },
    {
      id: 7,
      name: '茯苓',
      pinyin: 'Fu Ling',
      aliases: ['云苓', '白茯苓'],
      category: '安神药',
      region: '华中',
      source: '多孔菌科真菌茯苓的干燥菌核',
      nature: '甘、淡，平',
      meridian: ['心', '肺', '脾', '肾'],
      efficacy: ['利水渗湿', '健脾宁心'],
      usage: '10-15g，健脾安神常规煎服。',
      caution: '虚寒精滑者慎用。',
      description: '茯苓药性平和，兼顾水湿代谢、脾胃运化和心神安定。',
      composition: ['茯苓多糖', '三萜类'],
      imageTone: '#8c7b59',
      formulaIds: [1, 2]
    },
    {
      id: 8,
      name: '金银花',
      pinyin: 'Jin Yin Hua',
      aliases: ['忍冬花', '银花'],
      category: '清热药',
      region: '华东',
      source: '忍冬科植物忍冬的干燥花蕾或初开的花',
      nature: '甘，寒',
      meridian: ['肺', '心', '胃'],
      efficacy: ['清热解毒', '疏散风热'],
      usage: '6-15g，温病初起可配连翘、薄荷。',
      caution: '脾胃虚寒及气虚疮疡脓清者慎用。',
      description: '金银花清热解毒力强，也能疏散风热，常用于温病、咽痛和疮痈。',
      composition: ['绿原酸', '木犀草苷'],
      imageTone: '#d4a64f',
      formulaIds: [5]
    }
  ],
  formulas: [
    {
      id: 1,
      name: '四君子汤',
      category: '补益剂',
      source: '太平惠民和剂局方',
      herbs: ['人参', '白术', '茯苓', '炙甘草'],
      effect: '益气健脾。',
      indication: '脾胃气虚，面色萎白，语声低微，食少便溏。',
      steps: ['人参为君，大补脾胃之气。', '白术健脾燥湿，茯苓渗湿助运。', '炙甘草益气和中并调和诸药。']
    },
    {
      id: 2,
      name: '归脾汤',
      category: '补益剂',
      source: '正体类要',
      herbs: ['人参', '黄芪', '白术', '当归', '茯苓', '远志', '酸枣仁', '龙眼肉', '炙甘草'],
      effect: '益气补血，健脾养心。',
      indication: '心脾气血两虚及脾不统血证。',
      steps: ['黄芪、人参、白术补脾益气。', '当归、龙眼肉养血。', '茯苓、远志、酸枣仁宁心安神。']
    },
    {
      id: 3,
      name: '麻黄汤',
      category: '解表剂',
      source: '伤寒论',
      herbs: ['麻黄', '桂枝', '杏仁', '甘草'],
      effect: '发汗解表，宣肺平喘。',
      indication: '外感风寒表实证，恶寒发热，无汗而喘。',
      steps: ['麻黄发汗宣肺。', '桂枝解肌发表，助麻黄发汗。', '杏仁降肺气，甘草调和诸药。']
    },
    {
      id: 4,
      name: '桃红四物汤',
      category: '理血剂',
      source: '医宗金鉴',
      herbs: ['当归', '川芎', '白芍', '熟地黄', '桃仁', '红花'],
      effect: '养血活血，祛瘀调经。',
      indication: '血虚兼血瘀之月经不调、痛经。',
      steps: ['四物汤养血调血。', '桃仁、红花增强活血祛瘀之力。']
    },
    {
      id: 5,
      name: '银翘散',
      category: '解表剂',
      source: '温病条辨',
      herbs: ['金银花', '连翘', '薄荷', '牛蒡子', '桔梗', '甘草'],
      effect: '辛凉透表，清热解毒。',
      indication: '温病初起，发热微恶风寒，咽痛口渴。',
      steps: ['金银花、连翘清热解毒。', '薄荷、牛蒡子疏散风热。', '桔梗宣肺利咽，甘草调和。']
    },
    {
      id: 6,
      name: '当归补血汤',
      category: '补益剂',
      source: '内外伤辨惑论',
      herbs: ['黄芪', '当归'],
      effect: '补气生血。',
      indication: '血虚发热，肌热面赤，烦渴欲饮。',
      steps: ['重用黄芪补气以生血。', '当归养血和营。']
    }
  ],
  tokens: [
    { name: 'Primary', value: '#2f7651', usage: '主按钮、重点节点、选中态' },
    { name: 'Teal', value: '#14766f', usage: '图谱关系、辅助图标' },
    { name: 'Amber', value: '#c67517', usage: '提示、方剂标签、药性信息' },
    { name: 'Text', value: '#16241d', usage: '正文与标题' },
    { name: 'Muted', value: '#627069', usage: '辅助文字' },
    { name: 'Line', value: 'rgba(22, 36, 29, 0.12)', usage: '边框和分隔线' }
  ]
};
